# Generated by Django 5.1.4 on 2025-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bayunca',
            options={'verbose_name': 'Bayunca 1', 'verbose_name_plural': 'Bayunca 1'},
        ),
        migrations.AlterModelOptions(
            name='lavilla',
            options={'verbose_name': 'La Villa', 'verbose_name_plural': 'La Villa'},
        ),
        migrations.AlterField(
            model_name='bayunca',
            name='REG_CA',
            field=models.IntegerField(help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='bayunca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='bayunca',
            name='direccion',
            field=models.IntegerField(blank=True, help_text='Dirección IOA de IEC104 o registro MODBUS.', null=True),
        ),
        migrations.AlterField(
            model_name='bayunca',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Información adicional en formato JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='bayunca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.'),
        ),
        migrations.AlterField(
            model_name='bayunca',
            name='value',
            field=models.FloatField(help_text='Valor medido o capturado del registro.'),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='REG_CA',
            field=models.IntegerField(help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='direccion',
            field=models.IntegerField(blank=True, help_text='Dirección IOA de IEC104 o registro MODBUS.', null=True),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Información adicional en formato JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del registro.'),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='value',
            field=models.FloatField(help_text='Valor medido o capturado del registro.'),
        ),
    ]
