# Generated by Django 5.1.4 on 2025-01-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_signs_direccion_alter_signs_metadata_and_more'),
        ('registros', '0002_alter_bayunca_options_alter_lavilla_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayunca',
            name='plant_id',
            field=models.ForeignKey(blank=True, help_text='Planta asociada al valor registrado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bayunca_values', to='plants.plant'),
        ),
    ]
