# Generated by Django 5.1.4 on 2025-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_lavilla_plant_id_alter_bayunca_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayunca',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='bayunca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='general',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='general',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='gonzaenergy',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='gonzaenergy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='lavilla',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='oldt',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='oldt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='produlesti',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='produlesti',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='sanpedro',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='sanpedro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='solchacras',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='solchacras',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='solhuaqui',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='solhuaqui',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='solsantonio',
            name='REG_CA',
            field=models.IntegerField(db_index=True, help_text='Código de Registro MODBUS o Dirección Común IEC104.'),
        ),
        migrations.AlterField(
            model_name='solsantonio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
    ]
