# Generated by Django 5.1.4 on 2025-02-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_bayunca_reg_ca_alter_bayunca_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bayunca',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='general',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gonzaenergy',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lavilla',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='oldt',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='produlesti',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sanpedro',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='solchacras',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='solhuaqui',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='solsantonio',
            name='updated_at',
        ),
    ]
