# Generated by Django 5.1.4 on 2025-01-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('potencia_dc', models.FloatField()),
                ('scada', models.CharField(blank=True, max_length=255, null=True)),
                ('protocolo_comunicacion', models.CharField(choices=[('IEC104', 'IEC104'), ('MODBUS', 'MODBUS')], max_length=10)),
                ('ip', models.GenericIPAddressField()),
                ('puerto', models.PositiveIntegerField()),
                ('api_url', models.URLField(max_length=255)),
                ('credenciales', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
