# Generated by Django 5.1.4 on 2025-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Planta registrada', 'verbose_name_plural': 'Plantas registradas'},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='api_url',
        ),
        migrations.AddField(
            model_name='plant',
            name='modelo',
            field=models.URLField(default='Bayunca1', help_text='Modelo dentro del backend que se usa para almacenar los registros.', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='active',
            field=models.BooleanField(default=False, help_text='Indica si la planta está activa o inactiva.'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='country',
            field=models.CharField(help_text='País donde se encuentra la planta.', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='credenciales',
            field=models.JSONField(blank=True, help_text='Credenciales para la autenticación en SCADA o API.', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ip',
            field=models.GenericIPAddressField(help_text='Dirección IP del sistema de control o SCADA de la planta.'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Información adicional en formato JSON. Para MODBUS: `start_address`, `max_registers`, `interval`. Para IEC104: `tick_rate_ms`, `command_timeout_ms`, `time_sender_sleep_ms`, `time_connect_ms`, `originator_address`.', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo de la planta fotovoltaica.', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='potencia_dc',
            field=models.FloatField(help_text='Potencia en corriente directa (DC) de la planta, expresada en MW.'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='protocolo_comunicacion',
            field=models.CharField(choices=[('IEC104', 'IEC104'), ('MODBUS', 'MODBUS')], help_text='Protocolo de comunicación utilizado (MODBUS o IEC104).', max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='province',
            field=models.CharField(help_text='Provincia o región donde está ubicada la planta.', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='puerto',
            field=models.PositiveIntegerField(help_text='Puerto de comunicación asociado al protocolo.'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scada',
            field=models.CharField(blank=True, help_text='Sistema SCADA utilizado para supervisión.', max_length=255, null=True),
        ),
    ]
