# Generated by Django 5.1.4 on 2025-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_options_remove_plant_api_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='modelo',
            field=models.CharField(default='Bayunca1', help_text='Modelo dentro del backend que se usa para almacenar los registros.', max_length=255),
        ),
    ]
