# Generated by Django 5.1.4 on 2025-01-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_created_at_plant_updated_at_signs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección asociada a la medición o registro, utilizada como identificador del punto de origen de los datos. En IEC104 es el Information Object Address (IOA). Puede ser nulo.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadatos adicionales del registro, utilizados para almacenar información extra sobre la medición. Aplica para Modbus e IEC104.', null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='object_type',
            field=models.CharField(blank=True, help_text="Tipo de objeto o registro utilizado. En IEC104 puede ser valores como 'M_ME_NC_1'. No aplica para Modbus.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='plant_id',
            field=models.ForeignKey(blank=True, help_text='Planta asociada a la señal registrada.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='plants.plant'),
        ),
        migrations.AlterField(
            model_name='signs',
            name='protocolo',
            field=models.CharField(blank=True, choices=[('IEC104', 'IEC104'), ('MODBUS', 'MODBUS')], help_text='Protocolo de comunicación utilizado para la transmisión de datos. Puede ser MODBUS o IEC104.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='reg_ca',
            field=models.CharField(blank=True, help_text='Número de registro utilizado para identificar la variable medida. En Modbus es la dirección de inicio (Start Address) y en IEC104 es la dirección común del objeto (Common Address).', max_length=255, null=True),
        ),
    ]
