# Generated by Django 5.1.4 on 2025-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_signs_direccion_alter_signs_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='modelo',
            field=models.CharField(choices=[('Bayunca1', 'Bayunca1'), ('LaVilla', 'LaVilla'), ('Oldt', 'Oldt'), ('Solchacras', 'Solchacras'), ('Solsantonio', 'Solsantonio'), ('Solhuaqui', 'Solhuaqui'), ('Sanpedro', 'Sanpedro'), ('Gonzaenergy', 'Gonzaenergy'), ('Produlesti', 'Produlesti'), ('General', 'General')], default='General', help_text='Modelo dentro del backend que se usa para almacenar los registros.', max_length=11),
        ),
    ]
