# Generated by Django 5.1.4 on 2025-01-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP del sistema de control o SCADA de la planta.', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo de la planta fotovoltaica.', max_length=255, unique=True),
        ),
    ]
