# Generated by Django 5.1.4 on 2025-01-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plant_ip_alter_plant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signs',
            options={'verbose_name': 'Señal registrada', 'verbose_name_plural': 'Señales registradas'},
        ),
        migrations.AddField(
            model_name='signs',
            name='active',
            field=models.BooleanField(default=False, help_text='Indica si la señal está activa o inactiva, es decir si se registra en la base de datos o se ignora.'),
        ),
    ]
