# Generated by Django 5.1.4 on 2025-01-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_signs_options_signs_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='active',
            field=models.BooleanField(default=True, help_text='Indica si la señal está activa o inactiva, es decir si se registra en la base de datos o se ignora.'),
        ),
    ]
