# Generated by Django 5.1.4 on 2025-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_signs_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo de la planta fotovoltaica.', max_length=15, unique=True),
        ),
    ]
