# Generated by Django 5.1.4 on 2025-01-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='protocolo',
            field=models.CharField(blank=True, choices=[('IEC104', 'IEC104'), ('MODBUS', 'MODBUS'), ('MODBUS-REV', 'MODBUS-REV')], help_text='Protocolo de comunicación utilizado para la transmisión de datos. Puede ser MODBUS o IEC104.', max_length=10, null=True),
        ),
    ]
