# Generated by Django 5.1.4 on 2025-01-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_alter_signs_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='protocolo_comunicacion',
            field=models.CharField(choices=[('IEC104', 'IEC104'), ('MODBUS', 'MODBUS'), ('MODBUS-REV', 'MODBUS-REV')], help_text='Protocolo de comunicación utilizado (MODBUS o IEC104).', max_length=10),
        ),
        migrations.AlterField(
            model_name='signs',
            name='protocolo',
            field=models.CharField(blank=True, choices=[('IEC104', 'IEC104'), ('MODBUS', 'MODBUS')], help_text='Protocolo de comunicación utilizado para la transmisión de datos. Puede ser MODBUS o IEC104.', max_length=10, null=True),
        ),
    ]
